# Generated by Django 4.0.4 on 2022-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactpageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/bg')),
            ],
        ),
    ]
