# Generated by Django 4.0.4 on 2022-06-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_contactpagebackground_contactbackground'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPageImage',
        ),
    ]
