# Generated by Django 4.1 on 2022-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_delete_contactbackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBackgrounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/bg/')),
            ],
        ),
    ]
