# Generated by Django 4.0.4 on 2022-05-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_contactimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactImages',
        ),
    ]
