# Generated by Django 4.0.4 on 2022-06-01 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_contactimages_galleryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='image2',
            field=models.ImageField(default='image', upload_to='posts/bg/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posts/bg/'),
            preserve_default=False,
        ),
    ]
