# Generated by Django 4.1 on 2022-09-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_homepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePicture',
        ),
    ]
