# Generated by Django 4.0.4 on 2022-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='posts/bg/')),
                ('image2', models.ImageField(upload_to='posts/bg/')),
                ('image3', models.ImageField(upload_to='posts/bg/')),
            ],
        ),
    ]
